backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "newsletter"
    label: "Newsletter"
    folder: "src/pages/newsletter"
    create: true
    slug: "{{year}}-{{month}}-newsletter-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "newsletter-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: Notification, name: notification, widget: object, fields: [{label: Display Notification, name: display, widget: boolean, default: true, hint: Turn the notification on or off.}, {label: Title, name: title, widget: string}, {label: Message, name: message, widget: string}, {label: Link, name: link, widget: string}]}
          - {label: Hero, name: hero, widget: object, fields: [{label: Tagline, name: tagline, widget: text}]}
          - {label: Affiliations, name: affiliations, widget: list, fields: [{label: Heading, name: heading, widget: string}, {label: Subheading, name: subheading, widget: string}, {label: Logo, name: image, widget: image, hint: Note: logo slider is hidden on smaller devices.}]}
          - {label: Section 1, name: section1, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Link Text, name: linkText, widget: string}, {label: Link Url, name: linkUrl, widget: string}]}
          - {label: Statistics, name: statistics, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Subheading, name: subheading, widget: string}, {label: Statistics, name: statistics, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Statistic, name: statistic, widget: string}, {label: Link Text, name: linkText, widget: string}, {label: Link Url, name: linkUrl, widget: string}]}]}
          - {label: Discount, name: discount, widget: object, fields: [{label: Display Discount, name: display, widget: boolean, default: true, hint: Turn the discount on or off.}, {label: Title, name: title, widget: string}, {label: Description, name: description, widget: string}, {label: Percentage, name: percentage, widget: string}, {label: Link Text, name: linkText, widget: string}, {label: Link Url, name: linkUrl, widget: string}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Author, name: author, widget: string}, {label: Quote, name: quote, widget: text}, {label: Image, name: image, widget: image}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
